/**
 * PDF 문서 생성 서비스
 * 
 * jsPDF를 사용하여 실제 통관 문서 PDF를 생성합니다.
 * - Commercial Invoice (상업송장)
 * - Packing List (패킹리스트)  
 * - Certificate of Origin (원산지증명서)
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { InvoiceData, PackingListData, CertificateOfOriginData } from '../types';

// ===== 공통 유틸 =====
function addHeader(doc: jsPDF, title: string, subtitle: string) {
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(subtitle, 105, 28, { align: 'center' });
  
  doc.setDrawColor(41, 98, 255);
  doc.setLineWidth(0.5);
  doc.line(15, 32, 195, 32);
}

function addPartyInfo(doc: jsPDF, label: string, party: { name: string; address: string; contact: string }, x: number, y: number): number {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text(label, x, y);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(party.name, x, y + 6);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(party.address, x, y + 12);
  doc.text(`Tel: ${party.contact}`, x, y + 18);
  
  return y + 24;
}

function addFooter(doc: jsPDF) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by PortAI - Smart Maritime Logistics & Customs Automation Platform', 105, pageHeight - 10, { align: 'center' });
  doc.text(`Generated: ${new Date().toLocaleString('ko-KR')}`, 105, pageHeight - 6, { align: 'center' });
}

// ===== Commercial Invoice PDF =====
export function generateInvoicePDF(data: InvoiceData): void {
  const doc = new jsPDF();
  
  addHeader(doc, 'COMMERCIAL INVOICE', 'COMMERCIAL INVOICE / TRADE DOCUMENT');
  
  // Document info
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Invoice No: ${data.invoiceNo}`, 150, 38);
  doc.text(`Date: ${data.date}`, 150, 44);
  doc.text(`Incoterms: ${data.incoterms}`, 150, 50);
  
  // Parties
  const yAfterExporter = addPartyInfo(doc, 'EXPORTER / SHIPPER', data.exporter, 15, 40);
  addPartyInfo(doc, 'IMPORTER / CONSIGNEE', data.importer, 15, yAfterExporter + 4);
  
  // Shipping info
  const shipY = yAfterExporter + 32;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('PORT OF LOADING:', 15, shipY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.loadPort, 60, shipY);
  
  doc.setFont('helvetica', 'bold');
  doc.text('PORT OF DISCHARGE:', 110, shipY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.dischargePort, 155, shipY);
  
  // Items table
  const tableY = shipY + 8;
  autoTable(doc, {
    startY: tableY,
    head: [['No.', 'Description', 'Qty', 'Unit', 'Unit Price', 'Amount']],
    body: data.items.map(item => [
      item.no.toString(),
      item.description,
      item.quantity.toLocaleString(),
      item.unit,
      `${data.currency} ${item.unitPrice.toFixed(2)}`,
      `${data.currency} ${item.amount.toFixed(2)}`
    ]),
    foot: [['', '', '', '', 'TOTAL:', `${data.currency} ${data.totalAmount.toFixed(2)}`]],
    theme: 'grid',
    headStyles: { fillColor: [41, 98, 255], textColor: 255, fontSize: 9 },
    footStyles: { fillColor: [240, 240, 255], textColor: [41, 98, 255], fontStyle: 'bold', fontSize: 10 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 65 },
      4: { halign: 'right' },
      5: { halign: 'right' }
    }
  });

  // Payment terms
  const finalY = (doc as any).lastAutoTable?.finalY || tableY + 60;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Terms:', 15, finalY + 10);
  doc.setFont('helvetica', 'normal');
  doc.text(data.paymentTerms, 55, finalY + 10);

  // Signature line
  doc.setDrawColor(200, 200, 200);
  doc.line(130, finalY + 35, 195, finalY + 35);
  doc.setFontSize(8);
  doc.text('Authorized Signature', 162, finalY + 40, { align: 'center' });
  
  addFooter(doc);
  doc.save(`Invoice_${data.invoiceNo}.pdf`);
}

// ===== Packing List PDF =====
export function generatePackingListPDF(data: PackingListData): void {
  const doc = new jsPDF();
  
  addHeader(doc, 'PACKING LIST', 'SHIPPING / PACKING DOCUMENT');
  
  doc.setFontSize(9);
  doc.text(`P/L No: ${data.plNo}`, 150, 38);
  doc.text(`Date: ${data.date}`, 150, 44);
  doc.text(`Invoice Ref: ${data.invoiceRef}`, 150, 50);
  
  addPartyInfo(doc, 'EXPORTER / SHIPPER', data.exporter, 15, 40);
  addPartyInfo(doc, 'IMPORTER / CONSIGNEE', data.importer, 15, 68);

  autoTable(doc, {
    startY: 96,
    head: [['No.', 'Description', 'Qty', 'Net Wt(kg)', 'Gross Wt(kg)', 'Dimensions']],
    body: data.items.map(item => [
      item.no.toString(),
      item.description,
      item.quantity.toLocaleString(),
      item.netWeight.toFixed(1),
      item.grossWeight.toFixed(1),
      item.dimensions
    ]),
    foot: [[
      '', 'TOTAL', 
      data.totalPackages.toLocaleString(),
      data.totalNetWeight.toFixed(1),
      data.totalGrossWeight.toFixed(1),
      ''
    ]],
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129], textColor: 255, fontSize: 9 },
    footStyles: { fillColor: [240, 255, 240], textColor: [16, 128, 80], fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 }
  });

  addFooter(doc);
  doc.save(`PackingList_${data.plNo}.pdf`);
}

// ===== Certificate of Origin PDF =====
export function generateCertificateOfOriginPDF(data: CertificateOfOriginData): void {
  const doc = new jsPDF();
  
  addHeader(doc, 'CERTIFICATE OF ORIGIN', 'ORIGIN CERTIFICATION DOCUMENT');
  
  doc.setFontSize(9);
  doc.text(`C/O No: ${data.coNo}`, 150, 38);
  doc.text(`Date: ${data.date}`, 150, 44);
  doc.text(`Invoice Ref: ${data.invoiceRef}`, 150, 50);
  
  addPartyInfo(doc, 'EXPORTER / MANUFACTURER', data.exporter, 15, 40);
  addPartyInfo(doc, 'IMPORTER / CONSIGNEE', data.importer, 15, 68);
  
  // Origin details table
  autoTable(doc, {
    startY: 96,
    head: [['Field', 'Details']],
    body: [
      ['Item Description', data.itemDescription],
      ['HS Code', data.hsCode],
      ['Quantity', data.quantity],
      ['Country of Origin', data.originCountry],
      ['Invoice Reference', data.invoiceRef]
    ],
    theme: 'grid',
    headStyles: { fillColor: [245, 158, 11], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    columnStyles: {
      0: { cellWidth: 50, fontStyle: 'bold' },
      1: { cellWidth: 130 }
    }
  });

  // Declaration
  const finalY = (doc as any).lastAutoTable?.finalY || 160;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'The undersigned hereby declares that the above-mentioned goods originate in the country shown above.',
    15, finalY + 15, { maxWidth: 180 }
  );

  doc.setDrawColor(200, 200, 200);
  doc.line(15, finalY + 40, 90, finalY + 40);
  doc.line(110, finalY + 40, 195, finalY + 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Signature of Exporter', 52, finalY + 45, { align: 'center' });
  doc.text('Stamp of Certifying Authority', 152, finalY + 45, { align: 'center' });
  
  addFooter(doc);
  doc.save(`CertificateOfOrigin_${data.coNo}.pdf`);
}
